version: "3"

networks:
  frontend:
  backend:
  
services:
  keycloak:
    image: jboss/keycloak:10.0.1
    ports:
      - 8081:8080
    networks:
      - frontend
      - backend
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/balambgarden-realm.json
  spring:
    build: ./app/Dockerfile
    ports:
      - 8080:8080
    networks:
      - backend